name: lrc
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - anthropic>=0.48.0
      - google-generativeai>=0.8.4
      - nltk>=3.9.1
      - numpy>=2.2.3
      - openai>=1.66.3
      - pandas>=2.2.3
      - plotly>=6.0.0
      - pyyaml>=6.0.2
      - scikit-learn>=1.6.1
      - sentence-transformers>=3.4.1
      - spacy>=3.8.4
      - streamlit>=1.43.0
      - pytest>=8.3.5